Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.61.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  # синхронизируем локальный и удаленный катологи
  config.vm.synced_folder "D:/VM/files", "/home/vagrant/synced_folder"
  # запускаем скрип из отдельного файла
  config.vm.provision "shell", path: "provision.sh"
  
  config.ssh.forward_agent = true
end
